-   id: pipenv-requirements-fixer
    name: Fix requirements
    description: fix requirements.txt based pipenv packages.
    entry: pipenv-requirements-fixer
    language: python
    files: ^(Pipfile|Pipfile.lock|requirements.txt)$
-   id: pipenv-dev-requirements-fixer
    name: Fix requirements development
    description: fix requirements-dev.txt based pipenv packages.
    entry: pipenv-dev-requirements-fixer
    language: python
    files: ^(Pipfile|Pipfile.lock|requirements-dev.txt)$
