-   id: pipenv-requirements-fixer
    name: fix requirements.txt
    description: fix requirements.txt based pipenv packages.
    entry: pipenv-requirements-fixer
    language: python
    files: ^(Pipfile|Pipfile.lock|requirements.txt)$
-   id: pipenv-dev-requirements-fixer
    name: fix requirements.txt
    description: fix requirements.txt based pipenv packages.
    entry: pipenv-requirements-fixer
    language: python
    files: ^(Pipfile|Pipfile.lock|requirements.txt)$
